// Generated by CoffeeScript 1.12.7
(function() {
  (function($) {
    $('#fullpage').fullpage();
    $('.down').on("click", function() {
      return $.fn.fullpage.moveSectionDown();
    });
    $('.popup-link').on("click", function() {
      var currentHref;
      currentHref = $(this).attr('href');
      return $(currentHref).css({
        opacity: 1,
        zIndex: 1
      });
    });
    return $('.close').on("click", function() {
      return $(this).parents().eq(1).css({
        opacity: 0,
        zIndex: -1
      });
    });
  })(jQuery);

}).call(this);


var iframe1 = $('.video iframe')[0];
var iframe2 = $('.video iframe')[1];
var iframe3 = $('.video iframe')[2];
var player1 = $f(iframe1);
var player2 = $f(iframe2);
var player3 = $f(iframe3);

$('.close').on("click", function() {
   player1.api('pause');
   player2.api('pause');
   player3.api('pause');
});

//# sourceMappingURL=dev.js.map
